
import { GoogleGenAI } from "@google/genai";
import { GenerationMode, VideoGenerationConfig, VideoStyle, ImageStyle, ImageQuality } from '../types';

const getStyleInstruction = (style: ImageStyle, customStyle: string): string => {
  if (style === ImageStyle.DEFAULT) {
    return '';
  }
  if (style === ImageStyle.CUSTOM) {
    return customStyle ? ` The image must be in the following style: ${customStyle}.` : '';
  }
  if (style === ImageStyle.GOOGLE) {
    return ' The image must be in the Google style: vibrant, primary colors, clean lines, modern, minimalist, with a playful and friendly touch. Flat design with subtle shadows.';
  }
  return ` The image must be in a ${style.toLowerCase()} style.`;
};

const constructPrompt = (prompt: string, mode: GenerationMode): string => {
  switch (mode) {
    case GenerationMode.THUMBNAIL:
      return `Create a high-impact, VIRAL YouTube thumbnail base for: '${prompt}'. 
      COMPOSITION & CTR META:
      - SUBJECT: Exaggerated "shocked" expression. Wide eyes, open mouth, high emotion. Place subject on the far right or far left to leave clear space for text.
      - BACKGROUND: High-contrast gradient (e.g., Deep Red to Black). Use cinematic motion blur on background elements like YouTube logos, dollar signs, or abstract sparks.
      - LIGHTING: Aggressive studio rim lighting (Backlighting) in neon colors to separate subject from background.
      - STYLE: Super-sharp focus, HDR polished, 4K professional photography style. 
      - TEXT PREPARATION: Leave a significant "empty" zone for large text overlays.
      - ELEMENTS: Include subtle visual cues of "growth" or "urgency" if relevant.`;
    case GenerationMode.CARTOON:
      return `A masterpiece character illustration of '${prompt}' in a modern 3D Disney/Pixar style. Soft shadows, vibrant skin tones, and expressive storytelling features. Square aspect ratio.`;
    case GenerationMode.STORY_IMAGE:
      return `Cinematic concept art for: '${prompt}'. Focused on epic scale and emotional atmosphere. 9:16 format, no text.`;
    case GenerationMode.SOCIAL:
      return `Premium minimal social media post design for: '${prompt}'. Swiss-style typography and high-end texture. Square aspect ratio.`;
    case GenerationMode.VERTICAL_STORY:
      return `Dynamic vertical story layout for: '${prompt}'. 9:16 vertical ratio with modern design aesthetics.`;
    default:
      return prompt;
  }
};

export const generateImage = async (
  prompt: string, 
  mode: GenerationMode, 
  imageStyle: ImageStyle, 
  customImageStyle: string,
  quality: ImageQuality = ImageQuality.STANDARD
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  let fullPrompt = constructPrompt(prompt, mode);
  const styleInstruction = getStyleInstruction(imageStyle, customImageStyle);
  fullPrompt += styleInstruction;
  
  let aspectRatio: '16:9' | '1:1' | '9:16' = '16:9';
  if (mode === GenerationMode.CARTOON || mode === GenerationMode.SOCIAL) {
    aspectRatio = '1:1';
  } else if (mode === GenerationMode.VERTICAL_STORY || mode === GenerationMode.STORY_IMAGE) {
    aspectRatio = '9:16';
  }

  // Use gemini-2.5-flash-image for standard and gemini-3-pro-image-preview for high quality.
  // Both use the generateContent method which is more robust for general API keys.
  const model = quality === ImageQuality.STANDARD ? 'gemini-2.5-flash-image' : 'gemini-3-pro-image-preview';
  const imageSize = quality === ImageQuality.HIGH ? "2K" : quality === ImageQuality.ULTRA ? "4K" : "1K";

  const response = await ai.models.generateContent({
    model: model,
    contents: { parts: [{ text: fullPrompt }] },
    config: {
      imageConfig: {
        aspectRatio: aspectRatio,
        ...(model === 'gemini-3-pro-image-preview' ? { imageSize } : {})
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image was generated by the API.");
};

export const generateVideo = async (
  prompt: string, 
  config: VideoGenerationConfig, 
  onProgress?: (status: string) => void
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const stylePrompt = config.style === VideoStyle.DEFAULT ? 'animated' : config.style;
  const fullPrompt = `A high-quality, ${stylePrompt} style video of '${prompt}'. The video should be approximately ${config.duration} seconds long.`;

  if (onProgress) onProgress("Sending request to Gemini...");

  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt: fullPrompt,
    config: {
      numberOfVideos: 1,
      aspectRatio: config.aspectRatio,
      resolution: '720p',
    }
  });

  if (onProgress) onProgress("Video generation started...");

  const POLL_INTERVAL = 5000;
  let elapsedSeconds = 0;

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, POLL_INTERVAL));
    elapsedSeconds += POLL_INTERVAL / 1000;
    
    if (onProgress) {
        onProgress(`Rendering video... (~${elapsedSeconds}s elapsed)`);
    }

    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  if (onProgress) onProgress("Finalizing video...");

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;

  if (downloadLink) {
    return `${downloadLink}&key=${process.env.API_KEY}`;
  } else {
    throw new Error("No video was generated by the API or the operation failed.");
  }
};
